// Copyright IBM Corp. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Signer is an autogenerated mock type for the Signer type
type Signer struct {
	mock.Mock
}

// Sign provides a mock function with given fields: msgBytes
func (_m *Signer) Sign(msgBytes []byte) ([]byte, error) {
	ret := _m.Called(msgBytes)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(msgBytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(msgBytes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
